# Generated by Django 3.1.1 on 2022-03-28 22:54

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0008_auto_20220226_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Input file name', max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoltageHoldingRatio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uv_aging', models.CharField(choices=[('Before UV', 'Before Uv'), ('After UV', 'After Uv')], default='Before UV', max_length=10)),
                ('measure_voltage', models.FloatField(default=1.0)),
                ('measure_freq', models.FloatField(default=0.6)),
                ('measure_temperature', models.FloatField(default=60)),
                ('value', models.FloatField(default=0.0)),
                ('file_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reliabilities.file')),
                ('lc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.liquidcrystal')),
                ('pi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.polyimide')),
                ('seal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.seal')),
                ('vender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.vender')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UShapeAC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('value', models.FloatField()),
                ('time', models.FloatField()),
                ('temperature', models.FloatField()),
                ('file_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reliabilities.file')),
                ('lc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.liquidcrystal')),
                ('pi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.polyimide')),
                ('seal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.seal')),
                ('vender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.vender')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SealWVTR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('value', models.FloatField(default=0.0)),
                ('temperature', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('thickness', models.FloatField(default=0)),
                ('file_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reliabilities.file')),
                ('lc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.liquidcrystal')),
                ('pi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.polyimide')),
                ('seal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.seal')),
                ('vender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.vender')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReliabilitySearchProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(default='Default', max_length=255, verbose_name='Profile Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Reliability Search Profile Address')),
                ('voltage_holding_ratio', models.FloatField(default=0.0)),
                ('voltage_holding_ratio_weight', models.FloatField(default=1.0, verbose_name='VHR Weight')),
                ('delta_angle', models.FloatField(default=90.0, verbose_name='Δ angle')),
                ('delta_angle_weight', models.FloatField(default=1.0, verbose_name='Δ angle Weight')),
                ('adhesion', models.FloatField(default=0.0, verbose_name='Adhesion')),
                ('adhesion_weight', models.FloatField(default=1.0, verbose_name='Adhesion Weight')),
                ('low_temperature_storage', models.FloatField(default=0.0, verbose_name='LTS')),
                ('low_temperature_storage_weight', models.FloatField(default=1.0, verbose_name='LTS Weight')),
                ('pressure_cooking_test', models.FloatField(default=0.0, verbose_name='PCT')),
                ('pressure_cooking_test_weight', models.FloatField(default=0.0, verbose_name='PCT Weight')),
                ('seal_wvtr', models.FloatField(default=0.0, verbose_name='Seal WVTR')),
                ('seal_wvtr_weight', models.FloatField(default=0.0, verbose_name='Seal WVTR Weight')),
                ('u_shape_ac', models.FloatField(default=0.0, verbose_name='U-Shape AC%')),
                ('u_shape_ac_weight', models.FloatField(default=0.0, verbose_name='U-Shape AC% Weight')),
                ('adhesion_venders', models.ManyToManyField(related_name='adhesion_venders', to='materials.Vender', verbose_name='Adhesion Venders')),
                ('delta_angle_venders', models.ManyToManyField(related_name='delta_angle_venders', to='materials.Vender', verbose_name='Δ angle Venders')),
                ('low_temperature_storage_venders', models.ManyToManyField(related_name='low_temperature_storage_venders', to='materials.Vender', verbose_name='LTS Venders')),
                ('pressure_cooking_test_venders', models.ManyToManyField(related_name='pressure_cooking_test_venders', to='materials.Vender', verbose_name='PCT Venders')),
                ('seal_wvtr_venders', models.ManyToManyField(related_name='seal_wvtr_venders', to='materials.Vender', verbose_name='Seal WVTR Venders')),
                ('u_shape_ac_venders', models.ManyToManyField(related_name='u_shape_ac_venders', to='materials.Vender', verbose_name='U-Shape AC% Venders')),
                ('voltage_holding_ratio_venders', models.ManyToManyField(related_name='voltage_holding_ratio_venders', to='materials.Vender', verbose_name='VHR Venders')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PressureCookingTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('value', models.FloatField(default=0.0)),
                ('measure_condition', models.CharField(help_text='measure condition', max_length=255)),
                ('test_vehical', models.CharField(help_text='test vehicle', max_length=255)),
                ('file_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reliabilities.file')),
                ('lc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.liquidcrystal')),
                ('pi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.polyimide')),
                ('seal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.seal')),
                ('vender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.vender')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LowTemperatureStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('storage_condition', models.CharField(choices=[('Bulk', 'Bulk'), ('Test Cell', 'Test Cell')], max_length=10)),
                ('slv_condition', models.FloatField(default=1.0)),
                ('measure_temperature', models.FloatField(default=-30.0)),
                ('value', models.FloatField(default=0.0)),
                ('file_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reliabilities.file')),
                ('jar_test_seal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lts_jar_test_seals', to='materials.seal')),
                ('lc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.liquidcrystal')),
                ('pi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.polyimide')),
                ('seal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.seal')),
                ('vender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.vender')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LowTemperatureOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('storage_condition', models.CharField(default='Test Cell', max_length=10)),
                ('slv_condition', models.FloatField(default=1.0)),
                ('measure_temperature', models.FloatField(default=-30.0)),
                ('value', models.IntegerField(choices=[(-1, 'N.A.'), (0, 'NG'), (1, 'Pass')], default=1)),
                ('file_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reliabilities.file')),
                ('jar_test_seal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lto_jar_test_seals', to='materials.seal')),
                ('lc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.liquidcrystal')),
                ('pi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.polyimide')),
                ('seal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.seal')),
                ('vender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.vender')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeltaAngle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('measure_voltage', models.FloatField(default=14.0)),
                ('measure_freq', models.FloatField(default=60.0)),
                ('measure_time', models.FloatField(default=72.0)),
                ('measure_temperature', models.FloatField(default=60.0)),
                ('value', models.FloatField(default=0.0)),
                ('file_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reliabilities.file')),
                ('lc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.liquidcrystal')),
                ('pi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.polyimide')),
                ('seal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.seal')),
                ('vender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.vender')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('adhesion_interface', models.CharField(help_text='enter condition', max_length=255)),
                ('method', models.CharField(max_length=255)),
                ('value', models.FloatField(default=0.0)),
                ('peeling', models.CharField(blank=True, help_text='Enter peeling interface.', max_length=40, null=True)),
                ('file_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reliabilities.file')),
                ('lc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.liquidcrystal')),
                ('pi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.polyimide')),
                ('seal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.seal')),
                ('vender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.vender')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
