# Generated by Django 3.1.1 on 2022-03-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reliabilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deltaangle',
            name='measure_temperature',
            field=models.FloatField(blank=True, default=60.0, null=True),
        ),
    ]
