# Generated by Django 3.1.1 on 2022-04-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reliabilities', '0002_auto_20220329_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhesion',
            name='unit',
            field=models.CharField(default='kgw', max_length=255),
        ),
        migrations.AddField(
            model_name='sealwvtr',
            name='time',
            field=models.FloatField(default=24),
        ),
        migrations.AddField(
            model_name='sealwvtr',
            name='unit',
            field=models.CharField(default='%', max_length=255),
        ),
    ]
