# Generated by Django 3.1.1 on 2022-04-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reliabilities', '0003_auto_20220403_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reliabilitysearchprofile',
            name='adhesion',
            field=models.FloatField(default=0.0, verbose_name='Adhesion(kgw) minimum'),
        ),
        migrations.AlterField(
            model_name='reliabilitysearchprofile',
            name='delta_angle',
            field=models.FloatField(default=90.0, verbose_name='Δ angle(°) maximum'),
        ),
        migrations.AlterField(
            model_name='reliabilitysearchprofile',
            name='low_temperature_storage',
            field=models.FloatField(default=0.0, verbose_name='LTS(days) minimum'),
        ),
        migrations.AlterField(
            model_name='reliabilitysearchprofile',
            name='pressure_cooking_test',
            field=models.FloatField(default=0.0, verbose_name='PCT(hours) minimum'),
        ),
        migrations.AlterField(
            model_name='reliabilitysearchprofile',
            name='seal_wvtr',
            field=models.FloatField(default=100.0, verbose_name='Seal WVTR(%) maximum'),
        ),
        migrations.AlterField(
            model_name='reliabilitysearchprofile',
            name='u_shape_ac',
            field=models.FloatField(default=100.0, verbose_name='U-Shape AC% maximum'),
        ),
        migrations.AlterField(
            model_name='reliabilitysearchprofile',
            name='voltage_holding_ratio',
            field=models.FloatField(default=0.0, verbose_name='VHR minimum'),
        ),
        migrations.AlterField(
            model_name='reliabilitysearchprofile',
            name='voltage_holding_ratio_weight',
            field=models.FloatField(default=1.0, verbose_name='VHR(%) Weight'),
        ),
    ]
