# Generated by Django 3.1.1 on 2022-04-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reliabilities', '0004_auto_20220419_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='reliabilitysearchprofile',
            name='material_type',
            field=models.CharField(choices=[('AAS', 'AAS'), ('TN', 'TN')], default='AAS', max_length=10),
        ),
    ]
