# Generated by Django 3.2.13 on 2022-06-30 01:52

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reliabilities', '0005_reliabilitysearchprofile_material_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Batch Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Batch Address')),
            ],
        ),
        migrations.AddField(
            model_name='adhesion',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reliabilities.batch'),
        ),
        migrations.AddField(
            model_name='deltaangle',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reliabilities.batch'),
        ),
        migrations.AddField(
            model_name='lowtemperatureoperation',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reliabilities.batch'),
        ),
        migrations.AddField(
            model_name='lowtemperaturestorage',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reliabilities.batch'),
        ),
        migrations.AddField(
            model_name='pressurecookingtest',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reliabilities.batch'),
        ),
        migrations.AddField(
            model_name='sealwvtr',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reliabilities.batch'),
        ),
        migrations.AddField(
            model_name='ushapeac',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reliabilities.batch'),
        ),
        migrations.AddField(
            model_name='voltageholdingratio',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reliabilities.batch'),
        ),
    ]
