from django.urls import path
from . import views
from .api import api

app_name = "materials"
urlpatterns = [
    path('',
        view=views.IndexView.as_view(),
        name='index'
    ),
    path(
        route='lc/list/',
        view=views.LiquidCrystalListView.as_view(),
        name='lc_list'
    ),
    path(
        route='lc/add/',
        view=views.LiquidCrystalCreateView.as_view(),
        name='lc_add'
    ),
    path(
        route='lc/<slug:slug>/',
        view=views.LiquidCrystalDetailView.as_view(),
        name='lc_detail'
    ),
    path(
        route='lc/<slug:slug>/update/',
        view=views.LiquidCrystalUpdateView.as_view(),
        name='lc_update'
    ),
    path(
        route='vender/list',
        view=views.VenderListView.as_view(),
        name='vender_list'
    ),
    path(
        route='upload/',
        view=views.MaterialsUploadView.as_view(),
        name='upload'
    ),
    path(
        'upload/success/',
        views.MaterialsUploadSuccessView.as_view(),
        name='upload_success'
    ),
    path(
        route='update/',
        view=views.MaterialsUpdateView.as_view(),
        name='update'
    )
    ,
    path(
        route='pi/list/',
        view=views.PolyimideListView.as_view(),
        name='pi_list'
    ),
    path(
        route='pi/add/',
        view=views.PolyimideCreateView.as_view(),
        name='pi_add'
    ),
    path(
        route='pi/<slug:slug>/',
        view=views.PolyimideDetailView.as_view(),
        name='pi_detail'
    ),
    path(
        route='pi/<slug:slug>/update/',
        view=views.PolyimideUpdateView.as_view(),
        name='pi_update'
    ),
    path(
        route='seal/list/',
        view=views.SealListView.as_view(),
        name='seal_list'
    ),
    path(
        route='seal/add/',
        view=views.SealCreateView.as_view(),
        name='seal_add'
    ),
    path(
        route='seal/<slug:slug>/',
        view=views.SealDetailView.as_view(),
        name='seal_detail'
    ),
    path(
        route='seal/<slug:slug>/update/',
        view=views.SealUpdateView.as_view(),
        name='seal_update'
    ),
    path(
        'template/',
        views.TemplateDownloadView.as_view(),
        name='template'
    ),
    path(
        'lc/refraction-index/upload/',
        views.RefractionIndexUploadView.as_view(),
        name='refraction_index_upload'
    ),
    path(
        'lc/refraction-index/update/success/',
        views.RefractionIndexUploadSuccessView.as_view(),
        name='refraction_index_upload_success'
    ),
    path(route="api/", view=api.urls),
]
