# Generated by Django 3.1.1 on 2022-03-09 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220302_1515'),
        ('opticals', '0002_rdlcellgap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdlcellgap',
            name='chip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rdl_cell_gap', to='products.chip'),
        ),
    ]
