# Generated by Django 3.1.1 on 2022-03-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opticals', '0003_auto_20220309_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdlcellgap',
            name='cell_gap',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
