# Generated by Django 3.1.1 on 2022-03-09 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opticals', '0005_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='axometricslog',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opticals.instrument'),
        ),
    ]
