# Generated by Django 3.1.1 on 2022-03-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opticals', '0007_rdlcellgap_instrument'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='axometricslog',
            constraint=models.UniqueConstraint(fields=('chip', 'measure_point'), name='chip_measure_point'),
        ),
    ]
