# Generated by Django 3.1.1 on 2022-03-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opticals', '0009_auto_20220311_1540'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='opticallog',
            name='opt_chip_measure_point',
        ),
        migrations.AddConstraint(
            model_name='opticallog',
            constraint=models.UniqueConstraint(fields=('chip', 'measure_point', 'voltage'), name='opt_unique'),
        ),
    ]
