# Generated by Django 3.1.1 on 2022-03-16 05:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productmodeltype_model_name'),
        ('materials', '0008_auto_20220226_1802'),
        ('opticals', '0013_auto_20220315_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpticalReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cell_gap', models.FloatField()),
                ('ito_slit', models.FloatField(blank=True, null=True)),
                ('tft_tech', models.CharField(choices=[(None, 'Unknown'), ('a_Si', 'a-Si'), ('LTPS', 'LTPS')], max_length=20)),
                ('lc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.liquidcrystal')),
                ('pi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.polyimide')),
                ('product_model_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.productmodeltype')),
                ('seal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.seal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
