# Generated by Django 3.1.1 on 2022-03-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opticals', '0014_opticalreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opticalreference',
            name='tft_tech',
            field=models.CharField(choices=[(None, 'Unknown'), ('a_Si', 'a-Si'), ('LTPS', 'LTPS')], max_length=20, verbose_name='TFT Tech'),
        ),
    ]
