# Generated by Django 3.1.1 on 2022-03-16 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_auto_20220226_1802'),
        ('products', '0012_productmodeltype_model_name'),
        ('opticals', '0015_auto_20220316_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opticalreference',
            name='cell_gap',
            field=models.FloatField(verbose_name='Cell Gap'),
        ),
        migrations.AlterField(
            model_name='opticalreference',
            name='ito_slit',
            field=models.FloatField(blank=True, null=True, verbose_name='ITO Slit'),
        ),
        migrations.AlterField(
            model_name='opticalreference',
            name='lc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.liquidcrystal', verbose_name='LC'),
        ),
        migrations.AlterField(
            model_name='opticalreference',
            name='pi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.polyimide', verbose_name='PI'),
        ),
        migrations.AlterField(
            model_name='opticalreference',
            name='product_model_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.productmodeltype', verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='opticalreference',
            name='seal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.seal', verbose_name='Seal'),
        ),
    ]
