# Generated by Django 3.1.1 on 2022-03-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opticals', '0017_opticalreference_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='opticalreference',
            name='contrast_ratio',
            field=models.FloatField(default=0, verbose_name='CR'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opticalreference',
            name='gray_to_gray',
            field=models.FloatField(default=0, verbose_name='G2G'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opticalreference',
            name='operate_voltage',
            field=models.FloatField(default=0, verbose_name='Vop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opticalreference',
            name='time_fall',
            field=models.FloatField(default=0, verbose_name='Tf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opticalreference',
            name='time_rise',
            field=models.FloatField(default=0, verbose_name='Tr'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opticalreference',
            name='transmittance',
            field=models.FloatField(default=0, verbose_name='T%'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opticalreference',
            name='w_x',
            field=models.FloatField(default=0, verbose_name='Wx'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opticalreference',
            name='w_y',
            field=models.FloatField(default=0, verbose_name='Wy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='responsetimelog',
            name='measure_point',
            field=models.SmallIntegerField(verbose_name='Point'),
        ),
        migrations.AlterField(
            model_name='responsetimelog',
            name='time_fall',
            field=models.FloatField(verbose_name='Tf'),
        ),
        migrations.AlterField(
            model_name='responsetimelog',
            name='time_rise',
            field=models.FloatField(verbose_name='Tr'),
        ),
    ]
