# Generated by Django 3.1.1 on 2022-03-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opticals', '0018_auto_20220316_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opticalreference',
            name='operate_voltage',
        ),
    ]
