# Generated by Django 3.1.1 on 2022-03-21 05:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20220318_1420'),
        ('materials', '0008_auto_20220226_1802'),
        ('opticals', '0019_remove_opticalreference_operate_voltage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpticalsFittingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cell_gap_upper', models.FloatField()),
                ('cell_gap_lower', models.FloatField()),
                ('response_time', picklefield.fields.PickledObjectField(editable=False)),
                ('time_rise', picklefield.fields.PickledObjectField(editable=False)),
                ('time_fall', picklefield.fields.PickledObjectField(editable=False)),
                ('w_x', picklefield.fields.PickledObjectField(editable=False)),
                ('w_y', picklefield.fields.PickledObjectField(editable=False)),
                ('is_valid', models.BooleanField(default=False)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.experiment')),
                ('lc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.liquidcrystal')),
            ],
        ),
        migrations.AddConstraint(
            model_name='opticalsfittingmodel',
            constraint=models.UniqueConstraint(fields=('experiment', 'lc'), name='opticals_scipy_model'),
        ),
    ]
