# Generated by Django 3.1.1 on 2022-03-21 13:21

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('opticals', '0020_auto_20220321_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='opticalsfittingmodel',
            name='lc_percent',
            field=picklefield.fields.PickledObjectField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opticalsfittingmodel',
            name='transmittance',
            field=picklefield.fields.PickledObjectField(default='', editable=False),
            preserve_default=False,
        ),
    ]
