# Generated by Django 3.1.1 on 2022-03-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opticals', '0022_opticalreference_w_capital_y'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opticalreference',
            name='w_capital_y',
        ),
        migrations.AddField(
            model_name='opticallog',
            name='w_capital_y',
            field=models.FloatField(default=0, verbose_name='WY'),
            preserve_default=False,
        ),
    ]
