# Generated by Django 3.1.1 on 2022-03-24 14:41

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('opticals', '0024_auto_20220324_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='opticalsfittingmodel',
            name='v_percent',
            field=picklefield.fields.PickledObjectField(default='', editable=False),
            preserve_default=False,
        ),
    ]
