# Generated by Django 3.1.1 on 2022-03-27 18:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('opticals', '0025_opticalsfittingmodel_v_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpticalSearchProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('response_time', models.FloatField(default=30.0)),
                ('delta_e_ab', models.FloatField(default=0.0)),
                ('contrast_ratio', models.FloatField(default=1500.0)),
                ('remark', models.TextField(choices=[('All', 'All'), ('Interpolation', 'Interpolation'), ('Extrapolation', 'Extrapolation')], default='Interpolation', max_length=20)),
                ('ref_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opticals.opticalreference', verbose_name='Ref Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
