# Generated by Django 3.1.1 on 2022-03-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opticals', '0026_opticalsearchprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opticalsearchprofile',
            name='contrast_ratio',
            field=models.FloatField(default=1500.0, verbose_name='CR'),
        ),
        migrations.AlterField(
            model_name='opticalsearchprofile',
            name='delta_e_ab',
            field=models.FloatField(default=0.0, verbose_name='ΔEab*'),
        ),
        migrations.AlterField(
            model_name='opticalsearchprofile',
            name='response_time',
            field=models.FloatField(default=30.0, verbose_name='RT'),
        ),
    ]
