# Generated by Django 3.1.1 on 2022-03-28 00:37

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opticals', '0028_opticalsearchprofile_lc_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='opticalsearchprofile',
            name='name',
            field=models.CharField(default='Default', max_length=255, verbose_name='Profile Name'),
        ),
        migrations.AddField(
            model_name='opticalsearchprofile',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='default', editable=False, populate_from='name', unique=True, verbose_name='Optical Search Profile Address'),
            preserve_default=False,
        ),
    ]
