# Generated by Django 3.1.1 on 2022-03-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opticals', '0029_auto_20220328_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='opticalsearchprofile',
            name='contrast_ratio_weight',
            field=models.FloatField(default=1.0, verbose_name='CR Weight'),
        ),
        migrations.AddField(
            model_name='opticalsearchprofile',
            name='delta_e_ab_weight',
            field=models.FloatField(default=1.0, verbose_name='ΔEab* Weight'),
        ),
        migrations.AddField(
            model_name='opticalsearchprofile',
            name='lc_percent_weight',
            field=models.FloatField(default=1.0, verbose_name='LC% Weight'),
        ),
        migrations.AddField(
            model_name='opticalsearchprofile',
            name='responst_time_weight',
            field=models.FloatField(default=1.0, verbose_name='RT Weight'),
        ),
    ]
