# Generated by Django 3.1.1 on 2022-03-28 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opticals', '0030_auto_20220328_0821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opticalsearchprofile',
            old_name='responst_time_weight',
            new_name='response_time_weight',
        ),
    ]
