# Generated by Django 3.1.1 on 2022-04-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opticals', '0031_auto_20220328_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opticalsearchprofile',
            name='contrast_ratio',
            field=models.FloatField(default=0.0, verbose_name='CR minimum'),
        ),
        migrations.AlterField(
            model_name='opticalsearchprofile',
            name='delta_e_ab',
            field=models.FloatField(default=100.0, verbose_name='ΔEab* minimum'),
        ),
        migrations.AlterField(
            model_name='opticalsearchprofile',
            name='lc_percent',
            field=models.FloatField(default=0.0, verbose_name='LC% minimum'),
        ),
        migrations.AlterField(
            model_name='opticalsearchprofile',
            name='response_time',
            field=models.FloatField(default=100.0, verbose_name='RT maximum'),
        ),
    ]
