# Generated by Django 3.1.1 on 2022-04-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opticals', '0034_auto_20220419_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opticalreference',
            name='cell_gap',
            field=models.FloatField(verbose_name='Cell Gap(um)'),
        ),
        migrations.AlterField(
            model_name='opticalreference',
            name='gray_to_gray',
            field=models.FloatField(verbose_name='G2G(ms)'),
        ),
        migrations.AlterField(
            model_name='opticalreference',
            name='ito_slit',
            field=models.FloatField(blank=True, null=True, verbose_name='ITO Slit(°)'),
        ),
        migrations.AlterField(
            model_name='opticalreference',
            name='time_fall',
            field=models.FloatField(verbose_name='Tf(ms)'),
        ),
        migrations.AlterField(
            model_name='opticalreference',
            name='time_rise',
            field=models.FloatField(verbose_name='Tr(ms)'),
        ),
    ]
