# Generated by Django 3.2.13 on 2022-05-05 08:37

import autoslug.fields
from django.db import migrations
import td_toolkits_v3.opticals.models


class Migration(migrations.Migration):

    dependencies = [
        ('opticals', '0035_auto_20220419_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opticalreference',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=td_toolkits_v3.opticals.models.OpticalReference.slug_gen, unique=True, verbose_name='opt ref addr'),
        ),
    ]
