# Generated by Django 3.2.13 on 2022-05-31 00:49

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import picklefield.fields
import td_toolkits_v3.opticals.models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_auto_20220421_1530'),
        ('products', '0013_auto_20220318_1420'),
        ('opticals', '0036_alter_opticalreference_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptFittingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=td_toolkits_v3.opticals.models.OptFittingModel.slug_gen, unique=True)),
                ('cell_gap_upper', models.FloatField()),
                ('cell_gap_lower', models.FloatField()),
                ('w_x', picklefield.fields.PickledObjectField(editable=False)),
                ('w_y', picklefield.fields.PickledObjectField(editable=False)),
                ('w_capital_y', picklefield.fields.PickledObjectField(editable=False)),
                ('lc_percent', picklefield.fields.PickledObjectField(editable=False)),
                ('transmittance', picklefield.fields.PickledObjectField(editable=False)),
                ('v_percent', picklefield.fields.PickledObjectField(editable=False)),
                ('r2', models.JSONField()),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.experiment')),
                ('lc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.liquidcrystal')),
                ('pi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.polyimide')),
                ('seal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.seal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
