# Generated by Django 3.2.13 on 2022-07-25 05:04

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('opticals', '0038_rtfittingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackLightUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(default='Default', max_length=255, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Back Light Unit Address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BackLightIntensity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('wavelength', models.FloatField(verbose_name='Wavelength(nm)')),
                ('value', models.FloatField(verbose_name='Value')),
                ('blu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_light_intensity', to='opticals.backlightunit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
