# Generated by Django 3.1.1 on 2022-02-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidcrystal',
            name='designed_cell_gap',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
