# Generated by Django 3.1.1 on 2022-02-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_auto_20220224_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vender',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name of Vender'),
        ),
    ]
