# Generated by Django 3.1.1 on 2022-02-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_auto_20220224_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidcrystal',
            name='density',
            field=models.FloatField(blank=True, null=True, verbose_name='d(g/cm^3)'),
        ),
        migrations.AddField(
            model_name='liquidcrystal',
            name='e_para',
            field=models.FloatField(blank=True, null=True, verbose_name='ε_∥'),
        ),
        migrations.AddField(
            model_name='liquidcrystal',
            name='e_perp',
            field=models.FloatField(blank=True, null=True, verbose_name='ε_⟂'),
        ),
        migrations.AddField(
            model_name='liquidcrystal',
            name='flow_viscosity',
            field=models.FloatField(blank=True, null=True, verbose_name='ν(mm^2/s'),
        ),
        migrations.AddField(
            model_name='liquidcrystal',
            name='k_11',
            field=models.FloatField(blank=True, null=True, verbose_name='K11(pN)'),
        ),
        migrations.AddField(
            model_name='liquidcrystal',
            name='k_22',
            field=models.FloatField(blank=True, null=True, verbose_name='K22(pN)'),
        ),
        migrations.AddField(
            model_name='liquidcrystal',
            name='k_33',
            field=models.FloatField(blank=True, null=True, verbose_name='K33(pN)'),
        ),
        migrations.AddField(
            model_name='liquidcrystal',
            name='n_e',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liquidcrystal',
            name='n_o',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liquidcrystal',
            name='rotational_viscosity',
            field=models.FloatField(blank=True, null=True, verbose_name='γ1(mPa*s)'),
        ),
        migrations.AddField(
            model_name='liquidcrystal',
            name='t_cn',
            field=models.FloatField(blank=True, null=True, verbose_name='Tcn(°C)'),
        ),
        migrations.AddField(
            model_name='liquidcrystal',
            name='t_ni',
            field=models.FloatField(blank=True, null=True, verbose_name='Tni(°C)'),
        ),
    ]
