# Generated by Django 3.1.1 on 2022-02-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_auto_20220224_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidcrystal',
            name='flow_viscosity',
            field=models.FloatField(blank=True, null=True, verbose_name='ν(mm^2/s)'),
        ),
    ]
