# Generated by Django 3.1.1 on 2022-02-24 15:59

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import td_toolkits_v3.materials.models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_auto_20220224_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name of Seal')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='LC Address')),
                ('vender', models.ForeignKey(default=td_toolkits_v3.materials.models.get_default_vender, on_delete=django.db.models.deletion.CASCADE, to='materials.vender')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Polyimide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name of Polyimide')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='LC Address')),
                ('vender', models.ForeignKey(default=td_toolkits_v3.materials.models.get_default_vender, on_delete=django.db.models.deletion.CASCADE, to='materials.vender')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
