# Generated by Django 3.1.1 on 2022-02-26 10:02

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_polyimide_seal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vender',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Vender Address'),
        ),
    ]
