# Generated by Django 3.1.1 on 2022-04-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_auto_20220226_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidcrystal',
            name='material_type',
            field=models.CharField(choices=[('AAS', 'AAS'), ('TN', 'TN')], default='AAS', max_length=10),
        ),
        migrations.AddField(
            model_name='polyimide',
            name='material_type',
            field=models.CharField(choices=[('AAS', 'AAS'), ('TN', 'TN')], default='AAS', max_length=10),
        ),
        migrations.AddField(
            model_name='seal',
            name='material_type',
            field=models.CharField(choices=[('AAS', 'AAS'), ('TN', 'TN')], default='AAS', max_length=10),
        ),
    ]
