# Generated by Django 3.2.13 on 2022-07-25 04:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_auto_20220421_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdinaryRefractionIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('wavelength', models.FloatField(help_text='in nm', verbose_name='Wavelength')),
                ('value', models.FloatField(verbose_name='Refraction Index')),
                ('lc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_exps', to='materials.liquidcrystal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtraordinaryRefractionIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('wavelength', models.FloatField(help_text='in nm', verbose_name='Wavelength')),
                ('value', models.FloatField(verbose_name='Refraction Index')),
                ('lc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ne_exps', to='materials.liquidcrystal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
