# Generated by Django 3.1.1 on 2022-02-27 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_auto_20220226_1802'),
        ('products', '0002_chip_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='chip',
            name='lc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.liquidcrystal'),
        ),
        migrations.AddField(
            model_name='chip',
            name='pi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.polyimide'),
        ),
        migrations.AddField(
            model_name='chip',
            name='seal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.seal'),
        ),
    ]
