# Generated by Django 3.1.1 on 2022-02-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220227_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chip',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='short id'),
        ),
    ]
