# Generated by Django 3.1.1 on 2022-03-02 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220302_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='product_type',
        ),
        migrations.AddField(
            model_name='experiment',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productmodeltype'),
        ),
    ]
