# Generated by Django 3.1.1 on 2022-03-09 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_factory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodeltype',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.factory'),
        ),
    ]
