# Generated by Django 3.1.1 on 2022-03-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productmodeltype_factory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='addr',
            field=models.CharField(blank=True, max_length=255, verbose_name='Factory Address(Physics)'),
        ),
    ]
