# Generated by Django 3.1.1 on 2022-03-14 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20220309_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='chip',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.condition'),
        ),
    ]
