# Generated by Django 3.1.1 on 2022-03-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_chip_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodeltype',
            name='model_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
