# Generated by Django 3.1.1 on 2022-03-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productmodeltype_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Experiment ID'),
        ),
    ]
